in numpy the number like 5 store as 000....00101 for 4 byte space (int 32)
buyt in numpy we can change it to int 16,int 8

list-->data store is not in contionus trend

numpy -->data store next to each other(contious memory)

SIMD use them --one formula to all entry in numpy 

In [2]:
import numpy as np
import sys
# numpy -->all sort of data , multi dimension array
# list-->many type can be in one,
# numpy--fixed type


In [4]:
a=np.array([1,3,5])
b=np.array([1,2,3])
c=a*b
print(c)

[ 1  6 15]


In [19]:
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
print(a.ndim,b.ndim)#tell dimensiom
print(a.shape,b.shape)#tell the (m,n) 
print(a.dtype,b.dtype)#tell the data type
print(a.itemsize,b.itemsize)#the size cover by the data entry in the array
print(a.size,b.size)#tells the number of element in the array
#note
# a.nbytes=a.size*a.itemsize #n.bytes tell the space taken by the data entry point
print(a.nbytes,b.nbytes)


1 2
(3,) (2, 3)
int64 int64
8 8
3 6
24 48


In [12]:
c=np.array([1,2,3],dtype='int16')
print(c)
print(c.dtype)
print(c.itemsize)

[1 2 3]
int16
2


In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])
print(a)
print(a[1,4])#you can fetch the data like this
print(a[0,:])
print(a[0])
print(a[1,:3])
print(a[1,3:])
print(a[::2])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
12
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7]
[ 8  9 10]
[11 12 13 14]
[[ 1  2  3  4  5  6  7]
 [15 16 17 18 19 20 21]]


In [ ]:
a[1,5]#get the specific element
a[0,:]#get the specific row
a[:,1]#get the specific column
#[start,end,stepsize]
a[0,1:6:2]#-->first row ,start from second element ,end at 6 ,step=2

# to change all element in row to 5
a[:,1]=5

        

In [57]:
aa=np.zeros(5)
ab=np.zeros((2,3,4))
print(ab)
print(aa)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[0. 0. 0. 0. 0.]


In [61]:
a1=np.ones((2,2))
a3=np.ones((2,2),dtype='int16')
a2=np.full((2,2),99)
print(a1)
print(a2)
print(a3)


[[1. 1.]
 [1. 1.]]
[[99 99]
 [99 99]]
[[1 1]
 [1 1]]


In [ ]:
np.full(a.shape,4)#this try to mimic the format of the array you gave as an reference


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#random number between 0 and 1
m2 =np.random.rand(4,2)#this will give the matrix of the desire matrix where each element is random
print(m2)
m1=np.random.rand(10)
print(m1)

[0.43211009 0.6202457  0.25549752 0.65437595 0.06536679 0.02903771
 0.18751614 0.37892936 0.81959389 0.08290911]


In [ ]:
np.random.random_sample(a.shape)#this way you can use the formate of matrix and produce the random number


array([[0.66922963, 0.54398287, 0.32620117, 0.08217962, 0.09169582,
        0.49914308, 0.33588717],
       [0.65100026, 0.97635935, 0.75042235, 0.42203808, 0.51635707,
        0.84823138, 0.82211409],
       [0.57219001, 0.35080407, 0.80487428, 0.82469743, 0.41811278,
        0.49810809, 0.76532048]])

In [66]:
np.random.randint(7,size=(3,3))

array([[5, 2, 0],
       [2, 4, 0],
       [4, 4, 1]], dtype=int32)

In [ ]:
np.random.randint(1,5,size=(5,5))#take starting value but not ending value

array([[3, 2, 2, 2, 1],
       [4, 4, 4, 3, 1],
       [2, 1, 4, 1, 2],
       [1, 1, 4, 2, 2],
       [4, 4, 3, 1, 2]], dtype=int32)

In [68]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
ar=np.array([1,2,3])
r1=np.repeat(ar,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [73]:
ar1=np.array([[1,2,3]])
r11=np.repeat(ar1,3,axis=0)
print(r11)  

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# excercise
yy=np.ones((5,5))
yy[1:4,1:4]=0
yy[2,2]=9
print(yy)
#--------------
# solutioin of the master
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
z[1,1]=9
print(z)
output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([1,2,3])
b=a
b[0]=100
print(a)

# ------------
c=b.copy()
c[0]=900
print(c)
print(b)#this time b won't get change even if we alter the values of b


[100   2   3]
[900   2   3]


In [86]:
g=np.array([1,23,44])
print(g+4)  #we can use +,-,*,/,**
print(np.sin(a))  

[ 5 27 48]
[-0.50636564  0.90929743  0.14112001]


In [87]:
np.cos(a)    

array([ 0.86231887, -0.41614684, -0.9899925 ])

In [ ]:
#linear algerbra
a=np.full((2,3),2)  
print(a)
b=np.full((3,2),2)

np.matmul(a,b)#multoiple two matrix

[[2 2 2]
 [2 2 2]]


array([[12, 12],
       [12, 12]])

In [91]:
c=np.identity(3)
d1=np.linalg.det(c)#this give the determinate of the matrix
print(d1)

1.0


In [ ]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])
print(np.max(a),np.min(a))
np.max(a,axis=1)
np.sum(a)
np.sum(a,axis=0)



21 1


In [ ]:
#reorganize array
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])
print(a.reshape((7,3)))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]


In [102]:
#vertical stacking vector
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack([v1,v2,v2]))
print(np.hstack((v1,v1,v2)))


[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]
[1 2 3 4 1 2 3 4 5 6 7 8]


In [107]:
#load data from file
file=np.genfromtxt('file.txt',delimiter=',')
file.astype('int32')
file#both are different dattype so they have to make copy rather than alter the original ones


array([7., 3., 7., 9., 1., 9., 3., 1., 7., 7., 7., 3., 4., 8., 6., 6., 2.,
       5., 8., 1.])

In [113]:
#indexing and boolean masking
print(file>4)
print(file[file>4])
print(len(file[file>4]))



[ True False  True  True False  True False False  True  True  True False
 False  True  True  True False  True  True False]
[7. 7. 9. 9. 7. 7. 7. 8. 6. 6. 5. 8.]
12


In [115]:
# you can index with the list
aa2=np.array([1,2,3,4,5,6,7,33,21,9])
aa2[[1,2,8]]

array([ 2,  3, 21])

In [121]:
xy=np.genfromtxt("file.txt",delimiter=',')
yz=np.any(xy>5,axis=0)
print(yz)

True


In [ ]:
arr = np.array([10, 20, 30, 40])
# Just do the comparison without np.any()
mask = arr > 25 
print(mask) # Output: [False, False,  True,  True]

In [122]:
np.all(xy>4,axis=0)

np.False_

In [ ]:
gh=((file>50)&(file<100))
print(gh)
print(~gh)#this give yiu the opposite answer you given
print(len(gh))

[False False False False False False False False False False False False
 False False False False False False False False]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]
20


In [134]:
# excersie
k2=list(range(1,31))
k1=np.array(k2)
print(k1.reshape((6,5)))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
